apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saas-pod
  template:
    metadata:
      labels:
        app: saas-pod
    spec:
      containers:
       - image: chsubhasis/saascopilot
         name: mysaascontainer
         ports:
         - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: my-saas-v3
spec:
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: saas-pod
  type: LoadBalancer
