apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: MyApp
    environment: prod
spec:
  containers:
  - name: myapp-container
    image: chsubhasis/saascopilot
    ports:
      - containerPort: 8001
    envFrom:
      - secretRef:
          name: my-api-keys
