name: CI Pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS_TOKEN }}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin

    - name: Verify Docker User and Build Image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
      run: |
        echo "DOCKER_USER: $DOCKER_USER"  # Debugging step
        docker build . -t $DOCKER_USER/saascopilot

    - name: Push the Docker Image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
      run: docker push $DOCKER_USER/saascopilot

    - name: Logout from Docker
      run: docker logout
