name: CI Pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS_TOKEN }}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin

    - name: Build the Docker image for saas copilot app
      run: docker build . -t $DOCKER_USER/saascopilot:copilot_humanize

    - name: Push the Docker Image
      run: docker push $DOCKER_USER/saascopilot:copilot_humanize

    - name: Logout from Docker
      run: docker logout
